spring.application.name=backend
spring.config.import=optional:file:./application-secrets.properties,optional:classpath:application-secrets.properties

# This will default to the environment variable GEMINI_API_KEY if set, 
# otherwise it will try to find gemini.api.key in application-secrets.properties
gemini.api.key=${GEMINI_API_KEY:}
